name: Eslint

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  check-url:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: 设置 Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: latest

      - name: 运行 Eslint
        shell: bash
        run: |-
          npm ci
          npm run lint
